[project]
name = 'fak-registry'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.dexterity-traits-v0'

[[project.requirements]]
contract_id = 'SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[[project.requirements]]
contract_id = 'SP1AY6K3PQV5MRT6R4S671NWW2FRVPKM0BR162CT6.leo-token'

[contracts.faktory-pool-registry]
path = 'contracts/faktory-pool-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.leo-pool-faktory]
path = 'contracts/leo-pool-faktory.clar'
clarity_version = 3
epoch = '3.1'

[contracts.pool-registry-faktory]
path = 'contracts/pool-registry-faktory.clar'
clarity_version = 3
epoch = '3.1'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
