[project]
name = 'fak-registry'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = [
   {contract_id = "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.dexterity-traits-v0", epoch = "3.0", clarity_version = 2},
   {contract_id = "SP2ZNGJ85ENDY6QRHQ5P2D4FXKGZWCKTB2T0Z55KS.charisma-traits-v1", epoch = "3.1", clarity_version = 3}
]
[contracts.leo-pool-faktory]
path = 'contracts/leo-pool-faktory.clar'
clarity_version = 3
epoch = 3.1

[contracts.pool-registry-faktory]
path = 'contracts/pool-registry-faktory.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
